name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  analyze:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck clang-tidy libsdl2-dev

    - name: Run Cppcheck
      run: |
        # Create output directory
        mkdir -p cppcheck_report

        # Run cppcheck with more focused checks
        cppcheck --enable=warning,performance,portability \
                 --suppress=missingInclude \
                 --suppress=missingIncludeSystem \
                 --suppressions-list=suppressions.txt \
                 -I/usr/include/SDL2 \
                 --library=.cppcheck \
                 --force \
                 --max-configs=10 \
                 --inline-suppr \
                 --output-file=cppcheck_report/report.txt \
                 --template="{file}:{line}: {severity}: {message}" \
                 main.c

        # Generate XML report for documentation
        cppcheck --enable=warning,performance,portability \
                 --suppress=missingInclude \
                 --suppress=missingIncludeSystem \
                 --suppressions-list=suppressions.txt \
                 -I/usr/include/SDL2 \
                 --library=.cppcheck \
                 --force \
                 --max-configs=10 \
                 --inline-suppr \
                 --xml \
                 --xml-version=2 \
                 main.c 2> cppcheck_report/report.xml

        # Display findings in console
        if [ -f cppcheck_report/report.txt ]; then
          echo "Cppcheck findings:"
          cat cppcheck_report/report.txt
          
          # Only fail on actual errors, not style or information
          if grep -iE "error:" cppcheck_report/report.txt; then
            echo "Found errors in static analysis"
            exit 1
          fi
        fi

    - name: Upload Cppcheck Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cppcheck-report
        path: cppcheck_report/
        if-no-files-found: warn
        retention-days: 90

    - name: Run clang-tidy
      run: |
        clang-tidy main.c -- -I/usr/include/SDL2 