name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  analyze:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck clang-tidy libsdl2-dev

    - name: Run Cppcheck
      run: |
        cppcheck --enable=all \
                 --suppress=missingInclude \
                 --suppress=missingIncludeSystem \
                 --error-exitcode=1 \
                 -I/usr/include/SDL2 \
                 --library=.cppcheck \
                 --verbose \
                 .

    - name: Run clang-tidy
      run: |
        clang-tidy main.c -- -I/usr/include/SDL2 