name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  analyze:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck clang-tidy libsdl2-dev

    - name: Run Cppcheck
      run: |
        # Create output directory
        mkdir -p cppcheck_report

        # Run cppcheck and generate both text and XML reports
        cppcheck --enable=all \
                 --suppress=missingInclude \
                 --suppress=missingIncludeSystem \
                 --suppressions-list=suppressions.txt \
                 --error-exitcode=1 \
                 -I/usr/include/SDL2 \
                 --library=.cppcheck \
                 --force \
                 --max-configs=10 \
                 --inline-suppr \
                 --output-file=cppcheck_report/report.txt \
                 main.c
        
        # Also generate XML report for potential future processing
        cppcheck --enable=all \
                 --suppress=missingInclude \
                 --suppress=missingIncludeSystem \
                 --suppressions-list=suppressions.txt \
                 -I/usr/include/SDL2 \
                 --library=.cppcheck \
                 --force \
                 --max-configs=10 \
                 --inline-suppr \
                 --xml \
                 --xml-version=2 \
                 main.c 2> cppcheck_report/report.xml
        
        # Display findings in console
        if [ -f cppcheck_report/report.txt ]; then
          echo "Cppcheck findings:"
          cat cppcheck_report/report.txt
          
          # Check for errors (looking for specific error patterns)
          if grep -iE "error:|warning:" cppcheck_report/report.txt; then
            exit 1
          fi
        fi

    - name: Upload Cppcheck Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cppcheck-report
        path: cppcheck_report/
        if-no-files-found: warn
        retention-days: 90

    - name: Run clang-tidy
      run: |
        clang-tidy main.c -- -I/usr/include/SDL2 