name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  analyze:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck clang-tidy libsdl2-dev python3-pip
        sudo pip3 install cppcheck-htmlreport

    - name: Run Cppcheck
      run: |
        cppcheck --enable=all \
                 --suppress=missingInclude \
                 --suppress=missingIncludeSystem \
                 --suppressions-list=suppressions.txt \
                 --error-exitcode=1 \
                 -I/usr/include/SDL2 \
                 --library=.cppcheck \
                 --force \
                 --max-configs=10 \
                 --inline-suppr \
                 --xml \
                 --xml-version=2 \
                 2> cppcheck_report.xml
        
        # Convert XML to readable format and also save as text
        cppcheck-htmlreport --file=cppcheck_report.xml --report-dir=cppcheck_report --source-dir=.
        
        # Display errors in console
        if [ -f cppcheck_report.xml ]; then
          echo "Cppcheck findings:"
          cat cppcheck_report.xml | grep -A 1 "error\|warning\|style\|performance"
          # Exit with error if there are error-level findings
          if grep -q 'severity="error"' cppcheck_report.xml; then
            exit 1
          fi
        fi

    - name: Upload Cppcheck Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cppcheck-report
        path: |
          cppcheck_report/
          cppcheck_report.xml
        if-no-files-found: ignore
        retention-days: 90

    - name: Run clang-tidy
      run: |
        clang-tidy main.c -- -I/usr/include/SDL2 